isHub: false
serverid: lobby1
hubOptions:
  world: 'world'
  gameServers:
    - lobby1
    - lobby2
    - lobby3
  hubNpcLocations:
    loc1:
      x: '-1.2'
      y: 1
      z '3'
    loc2:
      x: '-8.2'
      y: 5
      z '7'

lobbyOptions:
  world: 'neweb'
  locations:
    fireworks:
      one:
        x: '-8.2'
        y: 5
        z '7'
      two:
        x: '-8.2'
        y: 5
        z '7'
    winning:
      x: '-8.2'
      y: 5
      z '7'
    loosing:
      x: '-8.2'
      y: 5
      z '7'
    infiltrator:
      x: '-8.2'
      y: 5
      z '7'
    marksman:
      x: '-8.2'
      y: 5
      z '7'
    shredder:
      x: '-8.2'
      y: 5
      z '7'     
    blueSheep:
      x: '-8.2'
      y: 5
      z '7'
    redSheep:
      x: '-8.2'
      y: 5
      z '7'
    blueSpawn:
      x: '-8.2'
      y: 5
      z '7'
    redSpawn:
      x: '-8.2'
      y: 5
      z '7' 
    boundaryOne:
      x: '-8.2'
      y: 5
      z '7'
    boundaryTwo:
      x: '-8.2'
      y: 5
      z '7'
    lobbySpawn:
      x: '-8.2'
      y: 5
      z '7'      